//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IG2Patcher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringLUT {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringLUT() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IG2Patcher.Resources.StringLUT", typeof(StringLUT).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string Button_Exit {
            get {
                return ResourceManager.GetString("Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Patch.
        /// </summary>
        public static string Button_Patch {
            get {
                return ResourceManager.GetString("Button_Patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &apos;{0}&apos; could not be found..
        /// </summary>
        public static string Error_FileNotFound {
            get {
                return ResourceManager.GetString("Error_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error applying the patch: {0}.
        /// </summary>
        public static string Error_PatchFailed {
            get {
                return ResourceManager.GetString("Error_PatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Industry Giant II you have selected ({0}.{1}.{2}.{3}) is not supported by this version of the patcher, or the file is not an Industry Giant II program. Sorry :(.
        /// </summary>
        public static string Error_VersionNotSupported {
            get {
                return ResourceManager.GetString("Error_VersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patch successfully applied!.
        /// </summary>
        public static string Info_PatchSuccess {
            get {
                return ResourceManager.GetString("Info_PatchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bind the Multiplayer menu to the following button in main menu:.
        /// </summary>
        public static string Label_BindInfo {
            get {
                return ResourceManager.GetString("Label_BindInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Path:.
        /// </summary>
        public static string Label_GamePath {
            get {
                return ResourceManager.GetString("Label_GamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Version:.
        /// </summary>
        public static string Label_GameVersion {
            get {
                return ResourceManager.GetString("Label_GameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        public static string MenuButtons_Campaign {
            get {
                return ResourceManager.GetString("MenuButtons_Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string MenuButtons_Credits {
            get {
                return ResourceManager.GetString("MenuButtons_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuButtons_Exit {
            get {
                return ResourceManager.GetString("MenuButtons_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highscores.
        /// </summary>
        public static string MenuButtons_Highscores {
            get {
                return ResourceManager.GetString("MenuButtons_Highscores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string MenuButtons_Load {
            get {
                return ResourceManager.GetString("MenuButtons_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;none&gt;.
        /// </summary>
        public static string MenuButtons_None {
            get {
                return ResourceManager.GetString("MenuButtons_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuButtons_Options {
            get {
                return ResourceManager.GetString("MenuButtons_Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player.
        /// </summary>
        public static string MenuButtons_Player {
            get {
                return ResourceManager.GetString("MenuButtons_Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string MenuButtons_Resume {
            get {
                return ResourceManager.GetString("MenuButtons_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Singleplayer.
        /// </summary>
        public static string MenuButtons_Singleplayer {
            get {
                return ResourceManager.GetString("MenuButtons_Singleplayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tutorial.
        /// </summary>
        public static string MenuButtons_Tutorial {
            get {
                return ResourceManager.GetString("MenuButtons_Tutorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IG2 Program.
        /// </summary>
        public static string OpenDialog_Filter_IG2Program {
            get {
                return ResourceManager.GetString("OpenDialog_Filter_IG2Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select IG2 executable.
        /// </summary>
        public static string OpenDialog_IG2Title {
            get {
                return ResourceManager.GetString("OpenDialog_IG2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry Giant II - Multiplayer Patcher.
        /// </summary>
        public static string Title_Application {
            get {
                return ResourceManager.GetString("Title_Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer.
        /// </summary>
        public static string Title_Disclaimer {
            get {
                return ResourceManager.GetString("Title_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not existing.
        /// </summary>
        public static string Title_FileNotExisting {
            get {
                return ResourceManager.GetString("Title_FileNotExisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_PatchFailed {
            get {
                return ResourceManager.GetString("Title_PatchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Title_PatchSuccess {
            get {
                return ResourceManager.GetString("Title_PatchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version not supported.
        /// </summary>
        public static string Title_VersionNotSupported {
            get {
                return ResourceManager.GetString("Title_VersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISCLAIMER: You are patching the selected Industry Giant II program at your own risk. The creator of this patcher as well as United Independent Entertainment GmbH are not responsible for any damage done to the product or your computer. United Independent Entertainment GmbH is not involved in the creation of this patcher in any way. All rights to Industry Giant II are reserved by United Independent Entertainment GmbH.{0}{0}Do you want to continue?.
        /// </summary>
        public static string Warning_Disclaimer {
            get {
                return ResourceManager.GetString("Warning_Disclaimer", resourceCulture);
            }
        }
    }
}
